name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.2

      - name: Get IP
        id: get_ip
        run: |
            echo "::set-output name=ip_addr::$(curl -s ifconfig.me)"
      - name: Echo IP
        run: echo ${{steps.get_ip.outputs.ip_addr}}
